#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEXICON = ROOT / "words" / "lexicon.tsv"
GENERATED_DIR = ROOT / "words" / "generated"
INDEX_FILE = GENERATED_DIR / "lexicon-index.md"
TREE_FILE = GENERATED_DIR / "compound-tree.md"

REQUIRED_COLUMNS = ("form", "meaning", "category", "base", "status", "notes")
CORE_CATEGORIES = {"核", "複合核"}

@dataclass(frozen=True)
class Entry:
    form: str
    meaning: str
    category: str
    base: str
    status: str
    notes: str

    @property
    def parts(self) -> tuple[str, ...]:
        if not self.base or self.base == self.form:
            return ()
        return tuple(part for part in self.base.split("+") if part)

def read_lexicon() -> list[Entry]:
    with LEXICON.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        if reader.fieldnames is None:
            raise SystemExit("lexicon.tsv にヘッダがない")
        missing = [c for c in REQUIRED_COLUMNS if c not in reader.fieldnames]
        if missing:
            raise SystemExit("lexicon.tsv に必要な列がない: " + ", ".join(missing))
        return [Entry(form=(r.get("form") or "").strip(), meaning=(r.get("meaning") or "").strip(), category=(r.get("category") or "").strip(), base=(r.get("base") or "").strip(), status=(r.get("status") or "").strip(), notes=(r.get("notes") or "").strip()) for r in reader if any((r.get(c) or "").strip() for c in REQUIRED_COLUMNS)]

def validate(entries: list[Entry]) -> list[str]:
    errors = []
    forms = {}
    for e in entries:
        if not e.form:
            errors.append("空の form がある")
            continue
        if e.form in forms:
            errors.append(f"重複 form: {e.form} ({forms[e.form].meaning} / {e.meaning})")
        forms[e.form] = e
    for e in entries:
        for part in e.parts:
            if part not in forms:
                errors.append(f"未定義の構成要素: {e.form} ({e.meaning}) -> {part}")
    graph = {e.form: [p for p in e.parts if p in forms] for e in entries}
    visiting, visited = set(), set()
    def visit(node: str, trail: list[str]) -> None:
        if node in visited:
            return
        if node in visiting:
            start = trail.index(node) if node in trail else 0
            errors.append("複合関係の循環: " + " -> ".join(trail[start:] + [node]))
            return
        visiting.add(node); trail.append(node)
        for nxt in graph.get(node, []): visit(nxt, trail)
        trail.pop(); visiting.remove(node); visited.add(node)
    for node in graph: visit(node, [])
    return errors

def core_entries(entries: list[Entry]) -> list[Entry]:
    return [e for e in entries if e.category in CORE_CATEGORIES]

def render_index(entries: list[Entry]) -> str:
    lines = ["# 概念語彙一覧（自動生成）", "", "<!-- AUTO-GENERATED by tools/lexicon.py. DO NOT EDIT DIRECTLY. -->", "", "このファイルは `words/lexicon.tsv` から生成される。詳しい設計理由や意味範囲は `roots.md`、`nouns.md` などの手書き文書を参照する。", "", "| 語形 | 概念 | 種類 | 構成 | 状態 |", "|---|---|---|---|---|"]
    for e in core_entries(entries):
        base = e.base if e.base and e.base != e.form else "—"
        lines.append(f"| `{e.form}` | {e.meaning} | {e.category} | `{base}` | {e.status} |")
    lines.append("")
    return "\n".join(lines)

def render_tree(entries: list[Entry]) -> str:
    cores = core_entries(entries)
    by_form = {e.form: e for e in cores}
    children = {e.form: [] for e in cores}
    has_parent = set()
    for e in cores:
        for part in e.parts:
            if part in by_form:
                children.setdefault(part, []).append(e.form); has_parent.add(e.form)
    roots = [e.form for e in cores if e.form not in has_parent and children.get(e.form)]
    lines = ["# 複合語ツリー（自動生成）", "", "<!-- AUTO-GENERATED by tools/lexicon.py. DO NOT EDIT DIRECTLY. -->", "", "複合語は複数の親を持てるため、厳密には木ではなくDAG（有向非巡回グラフ）である。同じ概念が複数箇所に現れるのは正常である。", ""]
    def emit(node: str, prefix: str, path: tuple[str, ...]) -> None:
        e = by_form[node]; lines.append(f"{prefix}- `{e.form}` {e.meaning}")
        if node in path:
            lines.append(f"{prefix}  - ⚠ 循環参照"); return
        for child in children.get(node, []): emit(child, prefix + "  ", path + (node,))
    for root in roots:
        emit(root, "", ()); lines.append("")
    return "\n".join(lines)

def outputs(entries: list[Entry]) -> dict[Path, str]:
    return {INDEX_FILE: render_index(entries), TREE_FILE: render_tree(entries)}

def write_generated(entries: list[Entry], check_only: bool = False) -> int:
    stale = []
    for path, content in outputs(entries).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not check_only:
                path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content, encoding="utf-8")
    if stale and check_only:
        for p in stale: print(f"STALE: {p.relative_to(ROOT)}")
        return 1
    for p in stale: print(f"generated: {p.relative_to(ROOT)}")
    if not stale: print("generated files are up to date")
    return 0

def source_files() -> list[Path]:
    files = [ROOT / "README.md", ROOT / "symbols.md", LEXICON]
    for dirname in ("words", "grammar", "phonology"):
        base = ROOT / dirname
        if base.exists(): files.extend(p for p in base.rglob("*.md") if "generated" not in p.parts)
    return sorted(set(p for p in files if p.exists()))

def build_rename_map(entries: list[Entry], old: str, new: str) -> dict[str, str]:
    mapping = {e.form: e.form.replace(old, new) for e in entries if old in e.form}
    if old not in mapping: raise SystemExit(f"語形 `{old}` は lexicon.tsv に存在しない")
    resulting = {}
    for e in entries:
        candidate = mapping.get(e.form, e.form)
        if candidate in resulting and resulting[candidate] != e.form:
            raise SystemExit(f"rename 後に語形が衝突する: {resulting[candidate]} と {e.form} -> {candidate}")
        resulting[candidate] = e.form
    return mapping

def apply_mapping(text: str, mapping: dict[str, str]) -> str:
    keys = sorted(mapping, key=len, reverse=True)
    pattern = re.compile("|".join(re.escape(k) for k in keys))
    return pattern.sub(lambda m: mapping[m.group(0)], text)

def rename_code(old: str, new: str, dry_run: bool) -> int:
    entries = read_lexicon(); errors = validate(entries)
    if errors:
        for e in errors: print("ERROR: " + e, file=sys.stderr)
        return 1
    mapping = build_rename_map(entries, old, new)
    changed = []
    for path in source_files():
        before = path.read_text(encoding="utf-8"); after = apply_mapping(before, mapping)
        if before != after:
            changed.append(path)
            if not dry_run: path.write_text(after, encoding="utf-8")
    print(f"{old} -> {new}")
    for src, dst in sorted(mapping.items(), key=lambda x: (-len(x[0]), x[0])): print(f"  {src} -> {dst}")
    print("変更対象:")
    for p in changed: print("  " + str(p.relative_to(ROOT)))
    if dry_run:
        print("dry-run: ファイルは変更していない"); return 0
    entries = read_lexicon(); errors = validate(entries)
    if errors:
        for e in errors: print("ERROR: " + e, file=sys.stderr)
        return 1
    return write_generated(entries)

def main() -> int:
    p = argparse.ArgumentParser(description="mylung 語彙の検証・自動生成・語形変更")
    sub = p.add_subparsers(dest="command", required=True)
    sub.add_parser("check")
    g = sub.add_parser("generate"); g.add_argument("--check", action="store_true")
    r = sub.add_parser("rename"); r.add_argument("old"); r.add_argument("new"); r.add_argument("--dry-run", action="store_true")
    a = p.parse_args()
    if a.command == "check":
        errors = validate(read_lexicon())
        if errors:
            for e in errors: print("ERROR: " + e)
            return 1
        print("OK"); return 0
    if a.command == "generate":
        entries = read_lexicon(); errors = validate(entries)
        if errors:
            for e in errors: print("ERROR: " + e)
            return 1
        return write_generated(entries, a.check)
    return rename_code(a.old, a.new, a.dry_run)

if __name__ == "__main__": raise SystemExit(main())
